### ISSUE TITLE
Document how to expose ports on NiFi nodes with Kubernetes Services

### ISSUE THREAD

**Issue by razvan** [stackabletech/nifi-operator#317]
# Description

Nifi workflows can be triggered from custom REST [endpoints](https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-standard-nar/1.9.2/org.apache.nifi.processors.standard.HandleHttpRequest/). This [article](https://www.clearpeaks.com/exposing-data-in-a-restful-api-with-nifi/) provides an example on how this works.

For clients to be able to access these endpoints from outside of the Kubernetes cluster they need to be exposed with service objects.
This ticket contains a comment with an example on how this works further down.

We should initially add a short paragraph on this to our documentation to explain the fundamentals and give one or two brief examples.

At a later stage we can then investigate how to provide convenience functionality in our operator around this.
I have opened https://github.com/stackabletech/nifi-operator/issues/414 as a follow up ticket for the investigation/implementation of this.

**Comment by pipern** [comment]
Is this concern (how do external systems send data to NiFi, such as a NiFi ListenTCP processor) wider than just 'REST'? I don't think it's 'REST triggered workflows' specific?

Is there an answer today on how the NiFi pod is configured to expose TCP/UDP ports for the 'listen' processors which someone might add in to their NiFi data flow design?

**Comment by soenkeliebau** [comment]
Hi @pipern - this is indeed not REST specific, but covers pretty much every processor in NiFi that might want to expose ports.

Currently this in not implemented, we have two ideas on this that we are looking to code when the time is right:

1. Allow the user to specify ports that should be exposed in the NiFi cluster definition. So basically a hardcoded list provided by the user which we'll then translate into NodePorts (or similar things)
2. An active part in the NiFi operator which uses the NiFi rest api to look for processors that should be exposed and dynamically creates NodePorts/ClusterIPs/... for these processors. This could take various forms, either allow specifying "all processors of type Rest should be exposed" or define a custom property that the user needs to add and which the operator then looks for or any number of different methods.

I do like the second method, because it is much more integrated and works straight from the NiFi UI, but it is also the much more complex one to build.

Ideally we'd like to integrate whatever approach we take with our Listerer operator, so that [ListenerClasses](https://docs.stackable.tech/listener-operator/stable/listenerclass.html) can be used to define how ports should be exposed.

**Comment by soenkeliebau** [comment]
Hi @pipern - this is indeed not REST specific, but covers pretty much every processor in NiFi that might want to expose ports.

Currently this in not implemented, we have two ideas on this that we are looking to code when the time is right:

1. Allow the user to specify ports that should be exposed in the NiFi cluster definition. So basically a hardcoded list provided by the user which we'll then translate into NodePorts (or similar things)
2. An active part in the NiFi operator which uses the NiFi rest api to look for processors that should be exposed and dynamically creates NodePorts/ClusterIPs/... for these processors. This could take various forms, either allow specifying "all processors of type Rest should be exposed" or define a custom property that the user needs to add and which the operator then looks for or any number of different methods.

I do like the second method, because it is much more integrated and works straight from the NiFi UI, but it is also the much more complex one to build.

Ideally we'd like to integrate whatever approach we take with our Listerer operator, so that [ListenerClasses](https://docs.stackable.tech/listener-operator/stable/listenerclass.html) can be used to define how ports should be exposed.

**Comment by pipern** [comment]
Thanks @soenkeliebau . Is there an intermediate solution which works today - does the NiFiCluster CRD have a place to declare additional `pod.spec.containers[].ports`? Otherwise it is correct that right now, *no* listeners are possible with Stackable NiFi? (I've glanced through the source code for nifi-operator/crd but don't spot a place to mention additional ContainerPorts)

**Comment by soenkeliebau** [comment]
Hi @pipern you can simply use normal Kubernetes functionality in the interim. Anything that we could add to the operator would simply be a convenience layer around k8s anyway.


To give a concrete example, I've stood up a three node NiFi on a GKE cluster and created the following flow: 

![image](https://user-images.githubusercontent.com/1070361/212958154-941cef1d-e370-4d08-b37d-b789b242c062.png)

with the ListenTCP processor listening on port 8123.  Port 8123 lives only inside of the Kubernetes overlay network, so if I spin up a pod inside of Kubernetes I can do reach it via the internal ip:

**Comment by pipern** [comment]
Much appreciated @soenkeliebau . Might we rename this issue?

**Comment by soenkeliebau** [comment]
Sure thing, I would probably convert this to a docs ticket and open a development follow up ticket, does that sound good?

**Comment by soenkeliebau** [comment]
@pipern I have converted this issue to a docs issue and opened https://github.com/stackabletech/nifi-operator/issues/414 as a follow up implementation issue.
