### ISSUE TITLE
NiFi default resources docs differ from actual defaults

### ISSUE THREAD

**Issue by maltesander** [stackabletech/nifi-operator#541]
The docs for default resources and PVCs differ from what the operator sets as default
https://github.com/stackabletech/nifi-operator/blob/main/rust/crd/src/lib.rs#L321
vs
https://docs.stackable.tech/home/nightly/nifi/usage_guide/resource-configuration

Docs mention 2GB for all repos and less cpu.

Nightly and at least 23.11 affected.

## Issue checklist

This is a simple checklist of things to bear in mind when creating a new issue.

- [ ] Describe the use-case, as far is possible. For instance, using the pattern "As a XXXX, I would like XXXX to be able to do XXXX" helps to identify the feature as well as the problem it is intended to address.
- [ ] Indicate an approximate level of importance and urgency.
- [ ] Indicate if there is a known work-around until such time as the issue has been implemented.

**Comment by fhennig** [comment]
I think my preferred solution is to document the defaults in the CRD docs, and just point to the CRD reference for these default values. For example for the `flowfileRepo` PVC we could document the default on this property: https://github.com/stackabletech/nifi-operator/blob/main/rust/crd/src/lib.rs#L409

This would be an improvement because then it is already closer to the code. I think it would be even better if the definition of the default was even closer to the documentation of it.

**Comment by fhennig** [comment]
To simply fix this now I want to update the docs. We can think about a longer term solution afterwards:

- 23.7: https://github.com/stackabletech/nifi-operator/pull/547
- 23.11: https://github.com/stackabletech/nifi-operator/pull/548
